### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Photon89** [TNick/dot-editor#1]
I get an error when compiling this: http://pastebin.com/D3gcSzJw Running Arch Linux with QT 5.8.0 and g++ 6.3.1.

**Comment by TNick** [comment]
The code is using Qt 4.8.
I have not attempted building it using Qt 5.
Will look into it over the weekend.

**Comment by Photon89** [comment]
Thanks for the fast reply! QT4 is also available but the header files are sitting in /usr/include/qt4 rather than /usr/include/qt. Maybe the makefile can check which path is actually containing QT4 somehow? Sorry, I'm not a programmer, maybe I'm writing bullsh*t. :)

**Comment by TNick** [comment]
I haven't look at this code in a while.
Now that I opened CMakeLists.txt it looks like it is using Qt 5.
Will investigate :)

**Comment by Photon89** [comment]
Cool, thanks!

**Comment by Photon89** [comment]
Thanks for the quick fix! Are the source archives (http://tnick.github.com/dot-editor/distrib/1.1.1/source/dot-editor-1.1.1-Source.tar.bz2) also updated?

**Comment by TNick** [comment]
They are not; please use the download button on project page (**Clone or Download**) or use [this](https://github.com/TNick/dot-editor/archive/master.zip) direct link.

**Comment by Photon89** [comment]
Maybe it is possible to make a point release for the fix? The AUR package https://aur.archlinux.org/packages/dot-editor/  is based on the release version, not on GIT...

**Comment by TNick** [comment]
Absolutely. I haven't realized that there is a downstream package based on this project.
Will happen today or tomorrow.

**Comment by Photon89** [comment]
Well, there is nothing that is not in the AUR. 😃

**Comment by TNick** [comment]
Here we go: https://github.com/TNick/dot-editor/archive/1.1.3.tar.gz

**Comment by Photon89** [comment]
Perfect, thanks! Let's see how fast the package maintainer will react to your flag and bump the package version.
