### ISSUE TITLE
Please add "path to saved file" variable to "Generator" settings

### ISSUE THREAD

**Issue by Photon89** [TNick/dot-editor#3]
I hope, I'm not getting annoying with all the bug reports and feature requests lately. :) Would it be possible to add the path to the file, if the opened file is saved somewhere (and fall back to /tmp if the file is not saved yet) to the possible variables list in the generator settings? Then one could have the exported image right next to the .dot file which is usual in most TeX editors for example. Currently I need to compile the .dot file by hand if I don't want to search for the temporary output file in /tmp. Thanks!

**Comment by TNick** [comment]
> I hope, I'm not getting annoying with all the bug reports and feature requests lately. :) 

Kidding me? You're the one and only user. This is exciting. :))
At this point you may ask to include [this silly cat gif](http://ell.h-cdn.co/assets/16/41/1476455582-dln66.gif) and I would probably do it.

> Would it be possible to add the path to the file, if the opened file is saved somewhere (and fall back to /tmp if the file is not saved yet) to the possible variables list in the generator settings? 

I propose this:

- **simple mode**: the program works like it does now, like a text editor (it only keeps track of the text file); this is useful for .dot files inside source code trees where you want the actual image creation to be part of the build process

- **entangled mode**: the program always saves the image along with the .dot file
    - either option to save / load the path for the image from the comments at the top of the .dot file
    - or option to always save with same path and name but different extension
    - or option to ask the user for image path on first save
    - or option to do nothing until first "Save As..." image occurs.


> Currently I need to compile the .dot file by hand if I don't want to search for the temporary output file in /tmp. 

If you right-click on the image you have a save-as option.

> Thanks!

You too.

**Comment by Photon89** [comment]
Your proposals sound like a lot of coding work to implement them, I would be already very happy if there is a variable holding the saved file path. But of course your idea is even better!

> If you right-click on the image you have a save-as option.

Yep, but then I would have to "save-as" many times. I want to generate .svg files with hyperlinks and have them open in a web browser to test if everything is working as intended. In principle I could just open the file in /tmp with the browser in the beginning of a working session and that's it (the file would be autoupdated whenever the code changes, which is nice), I'm just used to have the output in the same folder as the code file from TeX editors. :)

**Comment by TNick** [comment]
There must be a misunderstanding somewhere.
The path towards the generated file is already in the generator settings: `$OUT`.

The generator page is a very simple thing that - maybe - should be read from bottom to top: you set the input (saved for arguments in `$IN`) and the output (saved for arguments in `$OUT`) . 

Those get used in the arguments. 

Arguments are used with to the program to generate content.

**Comment by Photon89** [comment]
Yep, I figured that out, but I couldn't find an option to set $OUT to the path where the .dot file is saved. The only variable which can be used in $OUT is $TEMP which is set to /tmp in Linux. I'd like to have something like $OUT=$PATH_OF_SAVED_FILE/$NAME_OF_SAVED_FILE.svg where $PATH_OF_SAVED_FILE is not /tmp but the path which I chose when saving the .dot file.

**Comment by TNick** [comment]
Ok, I see what you mean now.

**Comment by TNick** [comment]
Following variables are going to be available:

- ED_FILE_PATH: path of the file in editor (TEMP path if the file is new)
- ED_FILE_NAME: name of the file in editor
- CD: current directory of the program
- DATE: current date
- TIME: current time
- DATETIME: current date and time

Also, all environment variables.

**Comment by Photon89** [comment]
Perfect, thanks a lot!
